### ISSUE TITLE
Flute sounds are almost entirely gone after hitting the noteblock once

### ISSUE THREAD

**Issue by SplendidAlakey** [varun7654/ClientSideNoteblocks#8]
**MC** 1.20.4
**Client Side Noteblocks** 2.6

To reproduce enable the mod and place a noteblock on clay and hit it once (left-click). After that right-clicking or powering the noteblock with redstone will produce no sound, but left-clicking will. Disabling the mod resolves it. Restarting the game works until the block is hit again. The bug will affect all noteblocks in the world that are placed on clay, not just the one you hit.

https://github.com/varun7654/ClientSideNoteblocks/assets/86702831/c0c94ca1-2b61-4a7d-a059-066ad877ca6f

In the video I:

1. Right-click the noteblock 3 times - there's sound
2. Press the button once - there's sound
3. Left-click the noteblock once - there's sound
4. Right-click the noteblock 3 times - there's no sound
5. Press the button once - there's no sound
6. Disable the mod
7. Right-click the noteblock 3 times - there's sound
8. Press the button once - there's sound
9. Left-click the noteblock once - there's sound
10. Right-click the noteblock 3 times - there's sound
11. Press the button once - there's sound

The bug happens in both single-player and multi-player.

Not seeing anything relevant in logs, but just in case:  https://gist.github.com/SplendidAlakey/e1c1d61ffde0deadd86202f45271a300

**Comment by varun7654** [comment]
I was able to reproduce, but I don't think I see anything specific to clay. Do you also see this bug with other noteblocks?

**Comment by varun7654** [comment]
@SplendidAlakey Published a new version that I believe should fix this issue. Lmk if they're still any remaining issues.

**Comment by SplendidAlakey** [comment]
Will try it out later today, but just to answer your previous question - I was actually too fixated on clay, that I forgot to test other blocks. Initially, I thought it to be just clay, as that's what I was working with at the time and the other noteblocks kept playing, despite clay breaking. However, I now realize it must've been because I hit clay but not the others.
