### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [varun7654/ClientSideNoteblocks#9]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by varun7654** [comment]
The license permits you to do whatever you want with the mod as long as you share source code if you make changes! 

On a more practical level, just use modrinth's/curseforge's standard modpack tools so that I still get credits for the downloads :)
